name: Publish
on:
  # release:
  #   types: [created]
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org/'
        scope: '@tybys'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: npm install --ignore-scripts
    - run: npm publish --@tybys:registry=https://registry.npmjs.org/ --access public
